baseurl = "/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "RAISEE"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""

# number of words of summarized post content (default 70)
# summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[markup.goldmark.renderer]
    unsafe = true


[menu]


# Main menu
[[menu.main]]
    name       = "Rewards"
    # identifier = "menu.home"
    url        = "/rewards/"
    weight     = 1


# [[menu.main]]
#     name       = "Option 5: Portfolio"
#     url        = "/"
#     weight     = 5
#     parent     = "menu.home"

[[menu.main]]
    name       = "AWARENESS"
    identifier = "menu.features"
    url        = "/awareness/"
    weight     = 2

[[menu.main]]
    name       = "INVESTIGATION"
    identifier = "menu.portfolio"
    url        = "/investigation"
    weight     = 3

[[menu.main]]
    name       = "SAFETY"
    url        = "/safety/"
    weight     = 4

[[menu.main]]
    name       = "EDUCATION"
    url        = "/education/"
    weight     = 5


[[menu.main]]
    name       = "ELDERLY"
    url        = "/"
    weight     = 6



# Top bar social links menu

 [[menu.topbar]]
     weight = 1
     name = "Phone"
     url = "tel:+19734040657"
     pre = "<i class='fas fa-2x fa-phone'></i>"

# [[menu.topbar]]
#     weight = 2
#     name = "GitHub"
#     url = "https://github.com/devcows/hugo-universal-theme"
#     pre = "<i class='fab fa-2x fa-github'></i>"

# [[menu.topbar]]
#     weight = 3
#     name = "Facebook"
#     url = "http://facebook.com"
#     pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
     weight = 4
     name = "Twitter"
     url = "https://twitter.com/actconvenient"
     pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:HELP@Elderlyfraud.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>The RAISEE Organization is a charitable organization dedicated to the fight against elderly fraud.</p>"
    copyright = "RAISEE Organization is the property of Actually Convenient, LLC all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Raisee"

    logo = "img/logo.png"
    logo_small = "img/logo.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>RAISEE Organization</strong>
        <br>A charitable organization founded by:
        <br>Actually Convenient LLC
        <br>Registered in New Jersey
        <br>actuallyconvenient@gmail.com
      </p>
      """

[permalinks]
    blog = "/blog/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Please Do Not Wait.  Contact us TODAY!</p>
      """

[params.mission1]
    title = "PLEASE READ THIS SENATE TESTIMONY TO HELP UNDERSTAND WHAT WE ARE WORKING TO PREVENT-"
    subtitle = "https://www.aging.senate.gov/imo/media/doc/SCA_Stancik_7_17_19.pdf"

[params.mission2]
    title = "This senior lost her life savings and has to take care of a brain injured son-"
    subtitle = "https://www.10news.com/news/team-10/senior-loses-more-than-84k-to-amazon-internet-scam"

[params.mission3]
    title = "Seniors lost nearly $1 Billion dollars in 2020 to scams-"
    subtitle = "https://abcnews.go.com/Politics/senior-citizens-lost-billion-scams-year-fbi/story?id=78356859"

[params.see_more]
    enable = true
    icon = "fa-solid fa-bullhorn"
    title = "There are over 50 million senior citizens in the United States today."
    subtitle = "We need YOUR help!  Become a hero today by spreading the word, donating to the HERO fund, or by providing information on current scams. <br>   "
    link_url = "/rewards/"
    link_text = "Put an end to scammers!"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.



[params.clients]
    enable = false
    

[params.recent_posts]
    enable = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
